export const SOCIAL_ACCOUNTS_BASE_URL =
  "https://connect.mintbase.xyz/social-account/";

export const MB_SOCIAL_ACCOUNTS_AUTH_TOKEN =
  process.env.MB_SOCIAL_ACCOUNTS_AUTH_TOKEN;

export const PUBNUB_WALLID_SUBSCRIBE_KEY =
  process.env.NEXT_PUBLIC_PUBNUB_WALLID_SUBSCRIBE_KEY;

export const PUBNUB_WALLID_PUBLISH_KEY = process.env.NEXT_PUBLIC_PUBNUB_WALLID_PUBLISH_KEY;

export const PUBNUB_REQUEST_CHANNEL_BASE = process.env.NEXT_PUBLIC_PUBNUB_REQUEST_CHANNEL_BASE;
