import Head from 'next/head'
import Link from 'next/link'
import { RDF, RDFField, useRDF } from 'radix-declarative-form'
import { useState } from 'react'

type FormState = {
  title: string
  description: string
  photographer: string
  media: File
}

const fields: RDFField<FormState>[] = [
  {
    type: 'text',
    name: 'title',
    label: 'Title of creative license',
    placeholder: 'Rights managed',
    options: {
      required: 'Give the license a title'
    }
  },
  {
    type: 'text',
    name: 'photographer',
    label: 'Photographer',
    // placeholder: '',
    options: {
      required: 'Photographer is required'
    }
  },
  {
    type: 'multiline',
    name: 'description',
    label: 'Describe the work',
    placeholder: 'The vastness of the universe was channeled to produce this fine art'
  },
  {
    type:'media',
    name: 'media',
    label: 'Upload image preview (<30mb)'
  }
]

export default function Mint() {
  const [dataInFlight, setDataInFlight] = useState(false);
  const form = useRDF(fields, async (fd: FormData, state: FormState) => {
    setDataInFlight(true);
    try {
      // set JSON attributes from from state
      fd.set('attributes', JSON.stringify([
        {
          trait_type: "website",
          display_type: "website",
          value: "https://nearcon.org/"
        },
        {
          trait_type: "photographer",
          display_type: "string",
          value: state.photographer
        },
      ]));
      const postRequest = await fetch('https://ar.mintbase.xyz/reference', {
        method: 'POST',
        headers: { 'mb-api-key': 'licensing-example' },
        body: fd
      });

      const result = await postRequest.json();
      console.log('created arweave hash, ready 2 mint!', result);
      setDataInFlight(false);
    } catch (e) {
      setDataInFlight(false);
      console.error(e);

    }
  })
  return (
    <>
      <Head>
        <title>Create License</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <Link href="/">back home</Link>
        <h1>Mint a license</h1>
        <RDF<FormState>
          form={form}
          isInFlight={dataInFlight}
          submitButtonLabel='Create License'
          submitButtonLabelInFlight='Creating...'
        />
      </main>
    </>
  )
}
