import { WalletConnectButton } from "@/components/WalletConnectButton";
import Head from "next/head";
import Link from "next/link";
import { RDF, useRDF } from "radix-declarative-form";
import { FormFields, useFormFields } from "@/hooks/useFormFields";
import { useFormSubmit } from "@/hooks/useFormSubmit";
import { Header } from "@/components/Header";
import { useWallet } from "@mintbase-js/react";
import { MintingForm } from "@/components/MintingForm";

export default function Mint() {
  const { activeAccountId } = useWallet();

  return (
    <>
      <Head>
        <title>Create License</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="main">
        <Link href="/">back home</Link>
        {activeAccountId
          ? <MintingForm />
          : <div>Please connect a wallet to continue</div>
        }
      </main>
    </>
  );
}
