import Head from 'next/head'
import Link from 'next/link'

export default function Success() {
  return (
    <>
      <Head>
        <title>Transaction Success</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <h1>Success!</h1>
        <p>This is a transaction success redirect page. It will do the following:</p>
        <ul>
          <li>Displays a loader</li>
          <li>Uses RPC to validate the transaction went as planned.</li>
          <li>Polls the indexer depending on the transaction results to ensure expected data is present</li>
          <li>Displays the result of the checks</li>
        </ul>
        Go <Link href="/">back home</Link> or <Link href="/mint">mint again</Link>
      </main>
    </>
  )
}
